packages:
  - apps/*
  - packages/*
storeDir: .pnpm-store
autoInstallPeers: true
strictPeerDependencies: false
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
overrides:
  postcss: 8.5.23
  sharp: 0.35.3
